terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket = "simple-contact-form"
    key    = "prod/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_prometheus_workspace" "my_workspace" {
  alias = "simple-contact-form-prometheus-workspace"
}

resource "aws_key_pair" "app_server_key" {
  key_name   = "fullstack-ssh-key"
  public_key = tls_private_key.ssh_key.public_key_openssh
}

resource "aws_security_group" "web_sg" {
  name        = "fullstack_web_sg"
  description = "Allow HTTP, SSH, and Spring Boot traffic"

  lifecycle {
    create_before_destroy = false
  }

  #tfsec:ignore:aws-ec2-no-public-ingress-sgr
  ingress {
    description = "SSH for server management"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  #tfsec:ignore:aws-ec2-no-public-ingress-sgr
  ingress {
    description = "HTTP for Angular frontend"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # tfsec:ignore:aws-ec2-no-public-ingress-sgr
  ingress {
    description = "HTTPS for secure web traffic"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  #tfsec:ignore:aws-ec2-no-public-egress-sgr
  egress {
    description = "Allow required outbound application traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_prometheus_workspace" "telemetry_workspace" {
  alias = "fullstack-telemetry-workspace"

  tags = {
    Name = "FullStackTelemetry"
  }
}

resource "aws_iam_role" "ec2_prometheus_role" {
  name = "ec2_prometheus_remote_write_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
      }
    ]
  })
  lifecycle {
    create_before_destroy = false
  }
}

resource "aws_iam_policy" "prometheus_write_policy" {
  name        = "PrometheusRemoteWritePolicy"
  description = "Allows EC2 to send telemetry to AMP"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "aps:RemoteWrite",
        ]
        Effect   = "Allow"
        Resource = aws_prometheus_workspace.telemetry_workspace.arn
      }
    ]
  })
  lifecycle {
    create_before_destroy = false
  }
}

resource "aws_iam_role_policy_attachment" "attach_prometheus_policy" {
  role       = aws_iam_role.ec2_prometheus_role.name
  policy_arn = aws_iam_policy.prometheus_write_policy.arn
}

resource "aws_iam_instance_profile" "ec2_prometheus_profile" {
  name = "ec2_prometheus_instance_profile"
  role = aws_iam_role.ec2_prometheus_role.name
  lifecycle {
    create_before_destroy = false
  }
}

resource "aws_instance" "app_server" {
  ami           = "ami-0c7217cdde317cfec"
  instance_type = "t2.micro"

  key_name               = aws_key_pair.app_server_key.key_name
  vpc_security_group_ids = [aws_security_group.web_sg.id]

  iam_instance_profile = aws_iam_instance_profile.ec2_prometheus_profile.name

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 8
    delete_on_termination = false
    encrypted             = true
  }

  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }

  user_data = templatefile("script.sh", {
    prometheus_endpoint = aws_prometheus_workspace.telemetry_workspace.prometheus_endpoint
    app_name            = "contact-form"
    jar_filename        = "app.jar"
  })

  tags = {
    Name = "Form-FullStack-APP"
  }
}

output "ec2_public_ip" {
  description = "The public IP of your EC2 server"
  value       = aws_instance.app_server.public_ip
}

output "private_key" {
  description = "The private key generated by Terraform for SSH access"
  value       = tls_private_key.ssh_key.private_key_pem
  sensitive   = true
}

output "prometheus_endpoint" {
  description = "The URL for the Prometheus workspace"
  value       = aws_prometheus_workspace.telemetry_workspace.prometheus_endpoint
}
