server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name ${DOMAIN_SSL};

    root /var/www/contact-form/browser;
    index index.html index.csr.html;

    server_tokens off;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self';" always;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location ~ \.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        access_log off;
    }

    error_page 403 /index.csr.html;

    location = / {
        return 301 /home;
    }

    location / {
        try_files $uri $uri/ @angular;
    }

    location @angular {
        try_files /index.csr.html =404;
    }

    location /api/int/ {
        deny all;
    }

    location /api/ {
        proxy_pass http://localhost:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
